source 'https://rubygems.org'

# Gemfile
gem "sinatra"
gem "sinatra-contrib"
gem 'celluloid'
gem 'celluloid-io'
gem 'http'
gem 'sinatra-websocket'
gem "rake"
gem 'require_all', '~> 1.3.2'
gem 'awesome_print', '~> 1.6.1'
gem 'erubis'
gem 'thin'


gem 'json'
gem 'byebug'
